export const dictionaries = {
  ru:{overview:'Обзор',students:'Ученики',payments:'Оплаты',groups:'Группы',teachers:'Преподаватели',attendance:'Посещаемость',schedule:'Расписание',leads:'Лиды',reminders:'Напоминания',analytics:'Аналитика',settings:'Настройки',search:'Поиск ученика, преподавателя, группы…',welcome:'Добро пожаловать в',subtitle:'Единая лёгкая система для учебного центра.',addStudent:'Добавить ученика',
    branches:'Филиалы',manage:'Управлять',addBranch:'Добавить филиал',editBranch:'Изменить филиал',branchName:'Название филиала',city:'Город',address:'Адрес',save:'Сохранить',cancel:'Отмена',delete:'Удалить',
    addGroup:'Новая группа',editGroup:'Изменить группу',groupName:'Название группы',days:'Дни занятий',time:'Время',capacity:'Вместимость',room:'Аудитория',level:'Уровень',teacher:'Преподаватель',branch:'Филиал',groupCode:'Код группы (для Telegram-бота)',
    saveAndExit:'Сохранить и выйти',present:'Есть',late:'Опоздал',absent:'Нет',chooseGroup:'Выберите группу',myGroup:'Моя группа',language:'Язык',noGroup:'У вас пока нет назначенной группы',
    mon:'Пн',tue:'Вт',wed:'Ср',thu:'Чт',fri:'Пт',sat:'Сб',sun:'Вс',
    login:'Войти',loginSubtitle:'Academy OS · войдите в систему',loginSubtitleDemo:'Academy OS · выберите аккаунт (демо)',email:'Email',password:'Пароль',loggingIn:'Проверка…',roleNote:'Каждая роль видит только нужные ей разделы',showPassword:'Показать пароль',hidePassword:'Скрыть пароль',genericAuthError:'Неверный email или пароль',
    navWork:'Работа',navStudy:'Учебный процесс',navGrowth:'Рост',navSystem:'Система',collapseMenu:'Свернуть меню',staff:'Сотрудники',
    subGroups:'Нагрузка, вместимость, преподаватели и аудитории',subTeachers:'Группы, нагрузка, специализация и контакты',subLeads:'От заявки до записи в группу',subReminders:'Правила, очередь, шаблоны и журнал отправки',subSettings:'Аккаунт, язык интерфейса и интеграции',subSchedule:'Уроки, аудитории и конфликты',subStaff:'Управляйте логинами и паролями преподавателей и админов',subAnalytics:'Финансы, академика и воронка набора',subPayments:'Ежемесячные начисления, частичные оплаты и напоминания',subStudentsManage:'Карточки, группы, оплаты, посещаемость и контакты',subStudentsTeacher:'Ваши группы: карточки и посещаемость',subAttendance:'Отметка за урок — без отдельной тяжёлой LMS',
    seats:'мест',filled:'заполнено',newStudentBtn:'Новый',assignExistingBtn:'Из списка',botLinked:'бот подключён',botPending:'бот ожидает',assignToGroupTitle:'Прикрепить к группе',noUngrouped:'Нет учеников без группы. Сначала создайте нового или освободите ученика из другой группы.',pickStudent:'Ученик',attach:'Прикрепить',schedulePageTitle:'Расписание',newTeacherTitle:'Новый преподаватель',editItem:'Изменить'},
  uz:{overview:'Bosh sahifa',students:'O‘quvchilar',payments:'To‘lovlar',groups:'Guruhlar',teachers:'Ustozlar',attendance:'Davomat',schedule:'Jadval',leads:'Lidlar',reminders:'Eslatmalar',analytics:'Analitika',settings:'Sozlamalar',search:'O‘quvchi, ustoz yoki guruh qidiring…',welcome:'Xush kelibsiz',subtitle:'O‘quv markazi uchun yagona yengil tizim.',addStudent:'O‘quvchi qo‘shish',
    branches:'Filiallar',manage:'Boshqarish',addBranch:'Filial qo‘shish',editBranch:'Filialni tahrirlash',branchName:'Filial nomi',city:'Shahar',address:'Manzil',save:'Saqlash',cancel:'Bekor qilish',delete:'O‘chirish',
    addGroup:'Yangi guruh',editGroup:'Guruhni tahrirlash',groupName:'Guruh nomi',days:'Dars kunlari',time:'Vaqt',capacity:'Sig‘im',room:'Xona',level:'Daraja',teacher:'Ustoz',branch:'Filial',groupCode:'Guruh kodi (Telegram-bot uchun)',
    saveAndExit:'Saqlash va chiqish',present:'Keldi',late:'Kechikdi',absent:'Kelmadi',chooseGroup:'Guruhni tanlang',myGroup:'Mening guruhim',language:'Til',noGroup:'Sizga hali guruh biriktirilmagan',
    mon:'Du',tue:'Se',wed:'Cho',thu:'Pa',fri:'Ju',sat:'Sha',sun:'Ya',
    login:'Kirish',loginSubtitle:'Academy OS · tizimga kiring',loginSubtitleDemo:'Academy OS · tizimga kirishni tanlang (demo)',email:'Email',password:'Parol',loggingIn:'Tekshirilmoqda…',roleNote:'Har bir rol faqat o‘ziga kerakli bo‘limlarni ko‘radi',showPassword:'Parolni ko‘rsatish',hidePassword:'Parolni yashirish',genericAuthError:'Email yoki parol noto‘g‘ri',
    navWork:'Ish',navStudy:'O‘quv jarayoni',navGrowth:'O‘sish',navSystem:'Tizim',collapseMenu:'Menyuni yig‘ish',staff:'Xodimlar',
    subGroups:'Yuklama, sig‘im, ustozlar va xonalar',subTeachers:'Guruhlar, yuklama, mutaxassislik va aloqa',subLeads:'Arizadan guruhga yozilishgacha',subReminders:'Qoidalar, navbat, shablonlar va yuborish jurnali',subSettings:'Hisob, interfeys tili va integratsiyalar',subSchedule:'Darslar, xonalar va to‘qnashuvlar',subStaff:'Ustoz va admin login/parollarini shu yerdan boshqaring',subAnalytics:'Moliya, akademika va lidlar voronkasi',subPayments:'Oylik hisoblar, qisman to‘lovlar va eslatmalar',subStudentsManage:'Kartochkalar, guruhlar, to‘lovlar, davomat va aloqa',subStudentsTeacher:'Sizning guruhlaringiz: kartochkalar va davomat',subAttendance:'Dars uchun belgilash — alohida og‘ir LMSsiz',
    seats:'joy',filled:'to‘ldirilgan',newStudentBtn:'Yangi',assignExistingBtn:'Ro‘yxatdan',botLinked:'bot ulangan',botPending:'bot kutilmoqda',assignToGroupTitle:'Guruhga biriktirish',noUngrouped:'Guruhsiz o‘quvchilar yo‘q. Avval yangisini yarating yoki boshqa o‘quvchini guruhdan bo‘shating.',pickStudent:'O‘quvchi',attach:'Biriktirish',schedulePageTitle:'Jadval',newTeacherTitle:'Yangi ustoz',editItem:'Tahrirlash'},
  ar:{overview:'نظرة عامة',students:'الطلاب',payments:'المدفوعات',groups:'المجموعات',teachers:'المعلمون',attendance:'الحضور',schedule:'الجدول',leads:'العملاء المحتملون',reminders:'التذكيرات',analytics:'التحليلات',settings:'الإعدادات',search:'ابحث عن طالب أو معلم أو مجموعة…',welcome:'مرحباً بكم في',subtitle:'نظام خفيف وموحد لإدارة المركز التعليمي.',addStudent:'إضافة طالب',
    branches:'الفروع',manage:'إدارة',addBranch:'إضافة فرع',editBranch:'تعديل الفرع',branchName:'اسم الفرع',city:'المدينة',address:'العنوان',save:'حفظ',cancel:'إلغاء',delete:'حذف',
    addGroup:'مجموعة جديدة',editGroup:'تعديل المجموعة',groupName:'اسم المجموعة',days:'أيام الدراسة',time:'الوقت',capacity:'السعة',room:'القاعة',level:'المستوى',teacher:'المعلم',branch:'الفرع',groupCode:'رمز المجموعة (لبوت تيليجرام)',
    saveAndExit:'حفظ وخروج',present:'حاضر',late:'متأخر',absent:'غائب',chooseGroup:'اختر المجموعة',myGroup:'مجموعتي',language:'اللغة',noGroup:'لم يتم تعيين مجموعة لك بعد',
    mon:'إثنين',tue:'ثلاثاء',wed:'أربعاء',thu:'خميس',fri:'جمعة',sat:'سبت',sun:'أحد',
    login:'دخول',loginSubtitle:'Academy OS · تسجيل الدخول',loginSubtitleDemo:'Academy OS · اختر حساب (تجريبي)',email:'البريد الإلكتروني',password:'كلمة المرور',loggingIn:'جارٍ التحقق…',roleNote:'كل دور يرى فقط الأقسام التي يحتاجها',showPassword:'إظهار كلمة المرور',hidePassword:'إخفاء كلمة المرور',genericAuthError:'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    navWork:'العمل',navStudy:'العملية التعليمية',navGrowth:'النمو',navSystem:'النظام',collapseMenu:'طي القائمة',staff:'الموظفون',
    subGroups:'الحمل، السعة، المعلمون والقاعات',subTeachers:'المجموعات، الحمل، التخصص والتواصل',subLeads:'من الطلب إلى التسجيل في المجموعة',subReminders:'القواعد، الطابور، القوالب وسجل الإرسال',subSettings:'الحساب، لغة الواجهة والتكاملات',subSchedule:'الدروس، القاعات والتعارضات',subStaff:'إدارة بيانات دخول المعلمين والمشرفين من هنا',subAnalytics:'المالية، الأكاديميا وقمع العملاء المحتملين',subPayments:'الرسوم الشهرية والدفعات الجزئية والتذكيرات',subStudentsManage:'البطاقات، المجموعات، المدفوعات، الحضور والتواصل',subStudentsTeacher:'مجموعاتك: البطاقات والحضور',subAttendance:'تسجيل الحضور للدرس — بدون نظام إدارة تعلم ثقيل',
    seats:'مقعد',filled:'ممتلئ',newStudentBtn:'جديد',assignExistingBtn:'من القائمة',botLinked:'البوت متصل',botPending:'البوت في الانتظار',assignToGroupTitle:'إلحاق بالمجموعة',noUngrouped:'لا يوجد طلاب بدون مجموعة. أنشئ طالباً جديداً أو حرّر طالباً من مجموعة أخرى.',pickStudent:'الطالب',attach:'إلحاق',schedulePageTitle:'الجدول',newTeacherTitle:'معلم جديد',editItem:'تعديل'},
  en:{overview:'Overview',students:'Students',payments:'Payments',groups:'Groups',teachers:'Teachers',attendance:'Attendance',schedule:'Schedule',leads:'Leads',reminders:'Reminders',analytics:'Analytics',settings:'Settings',search:'Search a student, teacher, group…',welcome:'Welcome to',subtitle:'One lightweight system for the academy.',addStudent:'Add student',
    branches:'Branches',manage:'Manage',addBranch:'Add branch',editBranch:'Edit branch',branchName:'Branch name',city:'City',address:'Address',save:'Save',cancel:'Cancel',delete:'Delete',
    addGroup:'New group',editGroup:'Edit group',groupName:'Group name',days:'Class days',time:'Time',capacity:'Capacity',room:'Room',level:'Level',teacher:'Teacher',branch:'Branch',groupCode:'Group code (for Telegram bot)',
    saveAndExit:'Save and exit',present:'Present',late:'Late',absent:'Absent',chooseGroup:'Choose a group',myGroup:'My group',language:'Language',noGroup:'No group assigned to you yet',
    mon:'Mon',tue:'Tue',wed:'Wed',thu:'Thu',fri:'Fri',sat:'Sat',sun:'Sun',
    login:'Log in',loginSubtitle:'Academy OS · sign in',loginSubtitleDemo:'Academy OS · choose an account (demo)',email:'Email',password:'Password',loggingIn:'Checking…',roleNote:'Each role only sees the sections it needs',showPassword:'Show password',hidePassword:'Hide password',genericAuthError:'Email or password is incorrect',
    navWork:'Work',navStudy:'Learning',navGrowth:'Growth',navSystem:'System',collapseMenu:'Collapse menu',staff:'Staff',
    subGroups:'Load, capacity, teachers and rooms',subTeachers:'Groups, load, specialty and contact',subLeads:'From inquiry to group enrollment',subReminders:'Rules, queue, templates and send log',subSettings:'Account, interface language and integrations',subSchedule:'Lessons, rooms and conflicts',subStaff:'Manage teacher and admin logins from here',subAnalytics:'Finance, academics and lead funnel',subPayments:'Monthly charges, partial payments and reminders',subStudentsManage:'Cards, groups, payments, attendance and contact',subStudentsTeacher:'Your groups: cards and attendance',subAttendance:'Mark a lesson — no heavy separate LMS',
    seats:'seats',filled:'filled',newStudentBtn:'New',assignExistingBtn:'From list',botLinked:'bot linked',botPending:'bot pending',assignToGroupTitle:'Assign to group',noUngrouped:'No ungrouped students. Create a new one first, or free a student from another group.',pickStudent:'Student',attach:'Assign',schedulePageTitle:'Schedule',newTeacherTitle:'New teacher',editItem:'Edit'}
};

export const localeNames = { ru:'Русский', uz:'O‘zbek', ar:'العربية', en:'English' };

export function tr(locale,key){return dictionaries[locale]?.[key] ?? dictionaries.ru[key] ?? key}

export const weekDays = ['mon','tue','wed','thu','fri','sat','sun'];

export function formatSchedule(days, time, locale) {
  if (!days || !days.length) return time || '';
  return days.map(d => tr(locale, d)).join('/') + (time ? ' · ' + time : '');
}
